name: sort_key_generator
description: A starting point for Dart libraries or applications.
version: 0.2.0+1
homepage: https://github.com/mono0926/sort_key_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic_mono:
  test:
