name: sort_key_generator
description: A starting point for Dart libraries or applications.
version: 0.2.0
homepage: https://github.com/mono0926/sort_key_generator
author: Masayuki Ono <mono0926@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic:
  test:
