name: sort_key_generator
description: Generate value between passed two values. This is useful for sorting.
version: 0.2.1
homepage: https://github.com/mono0926/sort_key_generator

environment:
  sdk: ^3.0.0

dev_dependencies:
  pedantic_mono:
  test:
